## Homework 01 - Instructions

![](https://github.com/rpi-techfundamentals/hm-01-starter/blob/master/notsaved.png?raw=1)

**WARNING!!!  If you see this icon on the top of your COLAB sesssion, your work is not saved automatically.**


**When you are working on homeworks, make sure that you save often. You may find it easier to save intermident copies in Google drive. If you save your working file in Google drive all changes will be saved as you work. MAKE SURE that your final version is saved to GitHub.** 

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment graded from answers to questions and automated tests that should be run at the bottom. Be sure to clearly label all of your answers and commit final tests at the end.

## BEFORE YOU BEGIN

Please work through each of these notebooks, which will give you some understanding of the Google Colab environment.

### Working with Notebooks in Colaboratory
- [Overview of Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)


### Working with Data
Some of this is a bit more advanced, but at this point just make sure you know where the code is for how to upload and download a file. 

- [Loading data: Drive, Sheets, and Google Cloud Storage](https://colab.research.google.com/notebooks/io.ipynb)

## Run these Cells
This will setup the automated testing environment on Colab

In [1]:
files = "https://github.com/rpi-techfundamentals/hm-01-starter/raw/master/files.zip" 
!pip install git+https://github.com/data-8/Gofer-Grader && wget $files && unzip -o files.zip

Collecting git+https://github.com/data-8/Gofer-Grader
  Cloning https://github.com/data-8/Gofer-Grader to /tmp/pip-req-build-wla6aqz0
  Running command git clone -q https://github.com/data-8/Gofer-Grader /tmp/pip-req-build-wla6aqz0
Requirement already satisfied (use --upgrade to upgrade): gofer-grader==1.0.9 from git+https://github.com/data-8/Gofer-Grader in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from gofer-grader==1.0.9) (2.10.3)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from gofer-grader==1.0.9) (2.1.3)
Requirement already satisfied: tornado in /usr/local/lib/python3.6/dist-packages (from gofer-grader==1.0.9) (4.5.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->gofer-grader==1.0.9) (1.1.1)
Building wheels for collected packages: gofer-grader
  Building wheel for gofer-grader (setup.py) ... done
  Created wheel for gofer-grader: filename=gofer_grader-1.0.9-cp36-none-any.whl size=10169 sha256=cac073f7796318972bfc5f19c3c24e1c4cc302ef3f95213def0e02e770de03dd
  Stored in directory: /tmp/pip-ephem-wheel-cache-_eegipjv/wheels/9e/62/24/8563ae039051d6ba979557d1766bfebbda5dd08f8572e3e35d
Successfully built gofer-grader
--2020-01-19 22:19:45--  https://github.com/rpi-techfundamentals/hm-01-starter/raw/master/files.zip
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rpi-techfundamentals/hm-01-starter/master/files.zip [following]
--2020-01-19 22:19:45--  https://raw.githubusercontent.com/rpi-techfundamentals/hm-01-starter/master/files.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 401727 (392K) [application/zip]
Saving to: ‘files.zip.1’

files.zip.1         100%[===================>] 392.31K  --.-KB/s    in 0.03s

2020-01-19 22:19:46 (13.5 MB/s) - ‘files.zip.1’ saved [401727/401727]

Archive:  files.zip
  inflating: hm01.ok
  inflating: md_result.png
  inflating: __MACOSX/._md_result.png
  inflating: notsaved.png
  inflating: __MACOSX/._notsaved.png
  inflating: tests/q01.py
  inflating: tests/q05.py
  inflating: tests/q04.py
  inflating: tests/__init__.py
  inflating: tests/qname.py
  inflating: tests/q02.py

In [0]:
#Run this. It initiates autograding. 
from client.api.notebook import Notebook
ok = Notebook('lab01.ok')
_ = ok.auth(inline=True)

**Question 1.** 

In the next cell, assign the value for `x` too 150.  Set the value for `y` to 13 times `x` , and set the value for `z` to `y` divided by `x` squared.

In [3]:
#enter your answer here
x=150
y=13*x
z=y/x**2
print(z)

0.08666666666666667

In [4]:
#Run this cell to see if you passed the test.  If it fails, you probably didn't run the above required code. 
_ = ok.grade('q01')

**Question 2.** 

Packages are really important compontent of most programming languages. 

In the overview, you learnned about tab completion as a way to explore python objects.  This can be really useful.  Let's use it to find the formula for the the factorial of 15. Assign the results to the variable `m`.

In [0]:
#we have to first import the math function to use tab completion. 
import math

In [6]:
#Assign the result to the variable m.
m = math.factorial(15)
m

1307674368000

In [7]:
#Run this cell to see if you passed the test.  If it fails, you probably didn't run the above required code. 
_ = ok.grade('q02')

**Question 3.** 

Markdown is a useful aspect of Jupyter Notebooks. 
- [Guide to Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)

Use what you learned about markdown to adjust the text below to create the following:
![](https://github.com/rpi-techfundamentals/hm-01-starter/blob/master/md_result.png?raw=1)

Header
For the above header, make it an h1 tag using markdown. 
#**Header**
Sub-Header

For the above sub-header, make it an h5 tag using markdown. 
#####Sub-Header
**Bold**

*Italics*

https://tw.rpi.edu//images/rpi-logo-red.jpg  
(Embed this image)
![Rensselear Logo](https://tw.rpi.edu//images/rpi-logo-red.jpg)

**Question 4.** 

### Installing Packages 
Python packages are an important part of data science and critical to leveraging the broader Python ecosystem.

You typically have two options when installing a package. You can install it with [Conda](http://anaconda.org) or [pip](https://pypi.org).

The `!` in a jupyter notebook means that the line is being processed on the `commmand line` and not by the Python interpreter. 

```
!conda install -c conda-forge <packagename>

!pip install <packagename>

```

If you try to import something and get an error, it is usally a tell that you need to install a package.

### Install the `fastparquet` Package to be able to work with Parquet Files
- CSV (comma delimited  files are great for humans to read and understand.  
- For "big data" though, it isn't a great long term storage option (inefficient/slow).
- Parquet is a type columnar storage format.  It makes dealing with lots of columns fast. 
- [fastparquet](https://fastparquet.readthedocs.io) is a Python package for dealing with Parquet files. 
- Apache Spark also natively reads Parquet Files. 
- Look [here](https://pypi.org/project/fastparquet/) for instructions on installing the fastparquet package.

In [8]:
#Install package for fastparquet here.

# conda install -c conda-forge fastparquet
pip install fastparquet

Requirement already satisfied: fastparquet in /usr/local/lib/python3.6/dist-packages (0.3.2)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.6/dist-packages (from fastparquet) (0.25.3)
Requirement already satisfied: numba>=0.28 in /usr/local/lib/python3.6/dist-packages (from fastparquet) (0.47.0)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from fastparquet) (1.17.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from fastparquet) (1.12.0)
Requirement already satisfied: thrift>=0.11.0 in /usr/local/lib/python3.6/dist-packages (from fastparquet) (0.13.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->fastparquet) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->fastparquet) (2.6.1)
Requirement already satisfied: llvmlite>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.28->fastparquet) (0.31.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from numba>=0.28->fastparquet) (42.0.2)

In [9]:
#This gets a parque file we can use to test. 
!wget https://github.com/rpi-techfundamentals/hm-01-starter/raw/master/Demographic_Statistics_By_Zip_Code.parq

--2020-01-19 22:19:49--  https://github.com/rpi-techfundamentals/hm-01-starter/raw/master/Demographic_Statistics_By_Zip_Code.parq
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rpi-techfundamentals/hm-01-starter/master/Demographic_Statistics_By_Zip_Code.parq [following]
--2020-01-19 22:19:49--  https://raw.githubusercontent.com/rpi-techfundamentals/hm-01-starter/master/Demographic_Statistics_By_Zip_Code.parq
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103532 (101K) [application/octet-stream]
Saving to: ‘Demographic_Statistics_By_Zip_Code.parq.3’

Demographic_Statist 100%[===================>] 101.11K  --.-KB/s    in 0.02s

2020-01-19 22:19:50 (4.72 MB/s) - ‘Demographic_Statistics_By_Zip_Code.parq.3’ saved [103532/103532]

In [10]:
#Run this to try to load the name.parq. It won't work unless you downloaded the file and installed the package. 
from fastparquet import ParquetFile  #This imports the package. 
pf = ParquetFile('Demographic_Statistics_By_Zip_Code.parq')
dfparq = pf.to_pandas()   #This changes the Parquet File object to a pandas dataframe. We will learn more about that later. 
dfparq  #Just listing the value prints it out.

     JURISDICTION NAME  ...  PERCENT PUBLIC ASSISTANCE TOTAL
0                10001  ...                              100
1                10002  ...                              100
2                10003  ...                              100
3                10004  ...                                0
4                10005  ...                              100
..                 ...  ...                              ...
231              12788  ...                              100
232              12789  ...                              100
233              13731  ...                              100
234              16091  ...                                0
235              20459  ...                                0

[236 rows x 46 columns]

In [11]:
#Run this cell to see if you passed the test.  
_ = ok.grade('q04')

**Question 5.** 

### Importing CSV into a Pandas Dataframe
- Comma delimited files are a common way of transmitting data. 
- Data for different columns is separated by a comma.
- It is possible to open a csv in different ways, but Pandas is the easiest.  
- Data structured like CSV's are extremely common and known as tabular data.
- Pandas will give access to many useful methods for working with data.  
- `pandas` is often imported as the abbreviated `pd`.

### Download CSV from Web to Colab using `wget`
Click this link [https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv?accessType=DOWNLOAD](https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv?accessType=DOWNLOAD)
to download the file to your local computer. 

To get the file onto the colab computational environment, the easiest way is to use wget.  If you have something on google drive, saving 

`!wget -O <filename you want to save to> <link to file>`

For example:
`!wget -O foo.csv https://data.us/122/?accessType=DOWNLOAD`

You can read more about wget [here](https://www.electrictoolbox.com/wget-save-different-filename/). 

**Note that this is not a strategy for data that needs to remain secured, as anyone with access to your notebook would also gain access to the file.**

In [12]:
#Insert your wget command here

!wget -O Demographic_Statistics_By_Zip_Code.csv https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv?accessType=DOWNLOAD

--2020-01-19 22:19:51--  https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv?accessType=DOWNLOAD
Resolving data.cityofnewyork.us (data.cityofnewyork.us)... 52.206.140.205, 52.206.140.199, 52.206.68.26
Connecting to data.cityofnewyork.us (data.cityofnewyork.us)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘Demographic_Statistics_By_Zip_Code.csv’

Demographic_Statist     [ <=>                ]  26.71K  --.-KB/s    in 0s

2020-01-19 22:19:52 (335 MB/s) - ‘Demographic_Statistics_By_Zip_Code.csv’ saved [27350]

In [13]:
# This will load the local name.csv file into a Pandas dataframe.  We will work with these a lot in the future.
import pandas as pd # This line imports the pandas package. 
dfcsv = pd.read_csv('Demographic_Statistics_By_Zip_Code.csv') 
dfcsv

     JURISDICTION NAME  ...  PERCENT PUBLIC ASSISTANCE TOTAL
0                10001  ...                              100
1                10002  ...                              100
2                10003  ...                              100
3                10004  ...                                0
4                10005  ...                              100
..                 ...  ...                              ...
231              12788  ...                              100
232              12789  ...                              100
233              13731  ...                              100
234              16091  ...                                0
235              20459  ...                                0

[236 rows x 46 columns]

In [14]:
#Run this cell to see if you passed the test.  
_ = ok.grade('q05')

### Git and Github
Do some investigation on your own and summarize 3 reasons why Git and Github are important tools for data scientists.

In [0]:
#Answer here
man1= """

#Answer here
1. Store projects in GitHub repositories to organize work, track changes, and provide a clear and well-documented path for analysis.

2. Run automated builds and tests for more complex projects to reduce bugs and maintain quality.

3. Collaborate with product developers and integrate machine learning features into their projects through forks, and allow others to 
validate and verify your findings or learn from your experiences.


"""

## Enter your information
This is required to make sure that you get credit for the assignment.

In [0]:
course="mgmt6560"   #course number
section="section2"          #section 
first_name="zeynep"   #For example, "jason"
last_name="tolun"    #For example, "kuruzovich"
student_id="tolunz"       #for example "kuruzj"
student_email="tolunz@rpi.edu"    #for example "kuruzj@rpi.edu"
collaborators = ""  #You can speak with others regarding the assignment, but all typed work must be your own.

In [17]:
#Run this cell to see if you passed the test.  
_ = ok.grade('qname')

## SUBMIT TO GITHUB 
Your final file must be submitted to GitHub.

In [18]:
#Please run this at end to show that all tests were passed. 
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]

## Homework Rubric
The following Rubric will be used to grade homwork. 
4 pts. x 6 questions. 
6 points for commit to github and 0 errors.
30 points total. 


```
The repository will be in the format:
https://github.com/rpi-intro-ml-app-<semester>-<year>/assignment-1-<your github id> 
```


### MAKE SURE THAT THIS ENTIRE NOTEBOOK RUNS WITHOUT ERRORS. TO TEST THIS DO RUNTIME --> RESTART AND RUN ALL

It should complete till the end.


This work is licensed under the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license agreement.